DROP TABLE IF EXISTS REIMBURSEMENT_TYPE CASCADE;
CREATE TABLE REIMBURSEMENT_TYPE(
	R_TYPE_ID SERIAL PRIMARY KEY,
	R_TYPE VARCHAR(250) NOT NULL
);

CREATE TABLE IF EXISTS USR CASCADE;
CREATE TABLE USR(
	USER_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(250) NOT NULL,
	PWD VARCHAR(250) NOT NULL,
	FIRSTNAME VARCHAR(250) NOT NULL,
	LASTNAME VARCHAR(250) NOT NULL,
	ROLL NUMERIC,
	APPROVED NUMERIC
);

CREATE TABLE IF EXISTS REIMBURSEMENTS CASCADE;
CREATE TABLE REIMBURSEMENTS(
	R_ID SERIAL PRIMARY KEY,
	AUTHOR INTEGER NOT NULL,
	R_RESOLVER INTEGER,
	AMOUNT NUMERIC,
	SUBMIT_DATE VARCHAR(100),
	RESOLVE_DATE VARCHAR(100),
	R_TYPE INTEGER,
	R_DESC VARCHAR(500),
	R_STATUS INTEGER,
	
	FOREIGN KEY (AUTHOR) REFERENCES USR(USER_ID),
	FOREIGN KEY (R_TYPE) REFERENCES REIMBURSEMENT_TYPE(R_TYPE_ID)
);

INSERT INTO USR (EMAIL, PWD, FIRSTNAME, LASTNAME, ROLL, APPROVED) VALUES ('bigboss25@gmail.com', 'pass', 'Big Boss', 'CEO', 2, 1);
INSERT INTO USR (EMAIL, PWD, FIRSTNAME, LASTNAME, ROLL, APPROVED) VALUES ('vpboss@gmail.com', 'pass', 'Other Boss', 'VP', 2, 1);

INSERT INTO REIMBURSEMENT_TYPE (R_TYPE) VALUES ('Lodging');
INSERT INTO REIMBURSEMENT_TYPE (R_TYPE) VALUES ('Travel');
INSERT INTO REIMBURSEMENT_TYPE (R_TYPE) VALUES ('Food');
INSERT INTO REIMBURSEMENT_TYPE (R_TYPE) VALUES ('Other');